Dict-like and array-like interfaces

In [2]:
some_dict = {"word": 1, "another word": 2, "some other word": 3}
some_dict.keys()

dict_keys(['word', 'another word', 'some other word'])

In [3]:
some_dict["something I made up"] = 123
some_dict["something I made up"]

123

In [4]:
some_dict.values()

dict_values([1, 2, 3, 123])

In [5]:
some_dict.items()

for key, value in some_dict.items():
    print(key, value)

word 1
another word 2
some other word 3
something I made up 123


In [6]:
for key in some_dict:
    print(key, some_dict[key])

word 1
another word 2
some other word 3
something I made up 123


In [7]:
import numpy as np

some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
some_array[0]  # okay
some_array[1]  # okay
some_array[9]  # okay
# some_array[10]  # not okay

9.9

In [8]:
len(some_array)
len(some_dict)
some_array[2:7]

array([2.2, 3.3, 4.4, 5.5, 6.6])

In [9]:
array3d = np.arange(2 * 3 * 5).reshape(2, 3, 5)
print(array3d)
print(array3d[:, 1:, 1:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 6  7  8  9]
  [11 12 13 14]]

 [[21 22 23 24]
  [26 27 28 29]]]
[[[ 2  3  4]
  [ 7  8  9]
  [12 13 14]]]


Exercise

In [10]:
print(array3d[:1, 0:, 2:])

[[[ 2  3  4]
  [ 7  8  9]
  [12 13 14]]]


Filtering with booleans and integers: "cuts"

In [11]:
some_array = np.array([0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
boolean_array = np.array(
    [True, True, True, True, True, False, True, False, True, False]
    )

some_array[boolean_array]

array([0. , 1.1, 2.2, 3.3, 4.4, 6.6, 8.8])

In [12]:
integer_array = np.array([0, 1, 2, 3, 4, 6, 8])

some_array[integer_array]

array([0. , 1.1, 2.2, 3.3, 4.4, 6.6, 8.8])

In [13]:
even_valued_items = some_array * 10 % 2 == 0

some_array[even_valued_items]

array([0. , 2.2, 4.4, 6.6, 8.8])